environment: &environment
  sample-var-01: ((sample-var-01))
  sample-var-02: ((sample-var-02))
  sample-var-03: ((sample-var-03))

jobs:
- name: echo-vars
  plan:
  - get: task
  - task: echo-vars
    file: task/tasks/echo-vars.yml
    vars:
      << : *environment

resources:
- name: task
  type: git
  source:
    uri: https://github.com/reinasroom/concourse-test.git