jobs:
- name: echo-vars
  plan:
  - get: task
  - task: echo-vars
    file: task/tasks/echo-vars.yml
    vars:
      sample-var: ((sample-var))

resources:
- name: task
  type: git
  source:
    uri: https://github.com/reinasroom/concourse-test.git