jobs:
- name: hello-world
  plan:
  - get: task
  - task: hello-world
    file: task/tasks/hello-world.yml
    vars:
      sample-var: ((sample-var))

resources:
- name: task
  type: git
  source:
    uri: https://github.com/reinasroom/concourse-test.git