platform: linux

image_resource:
    type: registry-image
    source: { repository: busybox }

params:
  sample-var-01: ((sample-var-01))
  sample-var-02: ((sample-var-02))

run:
  path: sh
  args:
  - -c
  - |
    echo ${sample-var-01} and ${sample-var-02}