platform: linux

image_resource:
    type: docker-image
    source: 
        repository: reinasroom/python-selenium-sample
        tag: ((image-tag))

params:
  MY_VAR1: ((sample-var-01))
  MY_VAR2: ((sample-var-02))
  MY_VAR3: ((sample-var-03))

run:
  path: sh
  args:
  - -c
  - |
    cd /app
    pytest fail.py
