environment: &environment
  sample-var-01: ((sample-var-01))
  sample-var-02: ((sample-var-02))
  sample-var-03: ((sample-var-03))

platform: linux

image_resource:
    type: registry-image
    source: { repository: busybox }

params:
  << : *environment

run:
  path: echo
  args: ["Hello world!"]