platform: linux

image_resource:
    type: registry-image
    source: { repository: busybox }

params:
  MY_VAR1: ((sample-var-01))
  MY_VAR2: ((sample-var-02))
  MY_VAR3: ((sample-var-03))

run:
  path: echo
  args: ["Hello world!"]