environment: &environment
  sample-var-01: ((sample-var-01))
  sample-var-02: ((sample-var-02))
  sample-var-03: ((sample-var-03))

jobs:
- name: sample-pipeline
  plan:
  - get: task
  - task: hello-world
    file: task/tasks/hello-world.yml
    vars:
      << : *environment
  - task: echo-vars
    file: task/tasks/echo-vars.yml
    vars:
      << : *environment

resources:
- name: task
  type: git
  source:
    uri: https://github.com/reinasroom/concourse-test.git