resources:
- name: concourse-test
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/reinasroom/concourse-test
    branch: master

jobs:
- name: set-self
  public: true
  plan:
  - get: concourse-test
    trigger: true
  - set_pipeline: self
    file: concourse-test/pipelines/set-pipelines.yml

- name: set-pipelines
  public: true
  plan:
  - get: concourse-test
    trigger: true
  - set_pipeline: sample-pipeline
    file: concourse-test/pipelines/sample-pipeline.yml
    var_files:
      - concourse-test/vars/vars.yml

- name: set-single
  public: true
  plan:
  - get: concourse-test
    trigger: true
  - set_pipeline: hello-world
    file: concourse-test/single/hello-world.yml
    var_files:
      - concourse-test/vars/vars.yml